### PR TITLE
improve catch child process errors

### PR DESCRIPTION
**Pull request by seeLuck**
Improve child process errors catching.

Not all child process errors are standard `Error` anyway.

### CODE REVIEW

**Comment by Paranoid-AF** [comment]
Hi, glad to see you reaching out!

Yes, I didn't realize such situation when I was writing this, and this needs to be fixed.
However, simply passing the error would make Error object losing its properties, including call stack, which is going to be painful for debugging.
So instead, I just made a new patch to it. When resolver's got an error, it would check if it's an Error object. If so, it would wrap it and pass the wrapped object to sender, and sender is going to produce a new Error object with the original properties. When it's not an Error object, the raw data would be passed.

Go ahead and check this out: 560c9512b6f215ca5bbe19ffd0bbb219c34ece4d
Also, it's already been publish on npm with version `2.2.0`

If you still have any concern, feel free to reply.

**Comment by seeLuck** [comment]
your solution is wonderful !

**Comment by seeLuck** [comment]
c

**Comment by seeLuck** [comment]
c

**Pull request closed without merging**
